case "${TERM}" in
	iterm2)
		TERM=xterm-256color
		COLORTERM=${COLORTERM:-truecolor}
		export GNUTERM=${GNUTERM:-png}
		;;
	wsltty)
		TERM=xterm-256color
		COLORTERM=${COLORTERM:-truecolor}
		export GNUTERM=${GNUTERM:-sixelgd}
		;;
	screen|xterm|xterm-256color)
		COLORTERM=${COLORTERM:-truecolor}
		export GNUTERM=${GNUTERM:-dumb}
		;;
	*)
		export GNUTERM=${GNUTERM:-dumb}
		;;
esac

